package org.apache.curator.x.rpc.idl.exceptions;

public enum ZooKeeperExceptionType
{
    SYSTEMERROR,
    RUNTIMEINCONSISTENCY,
    DATAINCONSISTENCY,
    CONNECTIONLOSS,
    MARSHALLINGERROR,
    UNIMPLEMENTED,
    OPERATIONTIMEOUT,
    BADARGUMENTS,
    APIERROR,
    NOAUTH,
    NOCHILDRENFOREPHEMERALS,
    INVALIDACL,
    AUTHFAILED,
    SESSIONEXPIRED,
    INVALIDCALLBACK,
    SESSIONMOVED,
    NOTREADONLY
}
